### ISSUE TITLE
Make it possible to download only a subset of subjects

### ISSUE THREAD

**Issue by alexenge** [eegverse/erpcore#3]
Thanks a lot, Matt, for creating this package!

I want to use the ERP CORE data for teaching and would like my students to be able to download only a subset of the data (e.g., only 1 or 2 subjects), instead of the whole data set. I've thought this might be useful for you or others as well, so I'm adding a PR that makes this possible.

**Comment by craddm** [comment]
Alex, so sorry I never saw these before! I'll merge them now. I don't know if they're still working - I hope so :) MAybe I'll have time again one day to revisit this package properly.
